# ----------------------------------------------------------------------------
#  Loads the current version number:
# ----------------------------------------------------------------------------
file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/version_prefix.txt" CMAKE_OPENRAVE_VERSION_NUMBER LIMIT_COUNT 1) # Read only the first line

# For example: "0.5.1"
string(REGEX MATCHALL "[0-9]+" CMAKE_OPENRAVE_VERSION_PARTS "${CMAKE_OPENRAVE_VERSION_NUMBER}")

list(GET CMAKE_OPENRAVE_VERSION_PARTS 0 OPENRAVE_VERSION_MAJOR)
list(GET CMAKE_OPENRAVE_VERSION_PARTS 1 OPENRAVE_VERSION_MINOR)
list(GET CMAKE_OPENRAVE_VERSION_PARTS 2 OPENRAVE_VERSION_PATCH)
set(CMAKE_OPENRAVE_FULL_VERSION "${OPENRAVE_VERSION_MAJOR}.${OPENRAVE_VERSION_MINOR}.${OPENRAVE_VERSION_PATCH}")
set(OPENRAVE_VERSION ${CMAKE_OPENRAVE_FULL_VERSION})
set(OPENRAVE_SOVERSION ${OPENRAVE_VERSION_MAJOR}.${OPENRAVE_VERSION_MINOR})
if(WIN32)
	if (MSVC)
		# 1700 = VC 11.0 (2012)
		# 1800 = VC 12.0 (2013)
		#           ... (13 was skipped!)
		# 1900 = VC 14.0 (2015)
		# 1910 = VC 14.1 (2017)
		math(EXPR MSVC_VERSION_3D "(${MSVC_VERSION}/10)-60")
		if (MSVC_VERSION_3D GREATER 120)
			math(EXPR MSVC_VERSION_3D "${MSVC_VERSION_3D}+10")
		endif()
		set(CMAKE_OPENRAVE_COMPILER_NAME "_msvc${MSVC_VERSION_3D}")
	else()
		set(CMAKE_OPENRAVE_COMPILER_NAME "_${CMAKE_CXX_COMPILER_ID}")
	endif()
	set(OPENRAVE_DLL_VERSION_POSTFIX "${OPENRAVE_VERSION_MAJOR}${OPENRAVE_VERSION_MINOR}${OPENRAVE_VERSION_PATCH}${CMAKE_OPENRAVE_COMPILER_NAME}_x${CMAKE_OPENRAVE_WORD_SIZE}")
else(WIN32)
	set(OPENRAVE_DLL_VERSION_POSTFIX "")
endif(WIN32)
